### ISSUE TITLE
[Question] License

### ISSUE THREAD

**Issue by quentinguidee** [boricj/numworks-rpn#12]
Bonjour,

Je suis en train de créer avec 2 autres contributeurs une version modifiée d'Epsilon, dénommée [Omega](https://github.com/Omega-Numworks/Omega). Nous souhaitons proposer des fonctionnalités que Numworks ne propose pas, et installable facilement (un contributeur a créé un installateur automatique pour cela).

Nous souhaitons intégrer une app RPN, et trouvons la votre assez avancée. Avons-nous le droit de réutiliser votre application dans notre version modifiée, bien sûr en vous mentionnant dans les contributeur ?

Merci d'avance,

Quentin G.

**Comment by boricj** [comment]
J'avoue ne pas m'être préoccupé de la licence de numworks-rpn car il y a deux points de vue légaux possibles:
- considérer que numworks-rpn est un dérivé d'epsilon, soumis à la licence d'origine
- considérer que numworks-rpn est une œuvre à part entière, non soumis à la licence d'origine

Dans le doute, je vais mettre une licence CC BY-NC-SA 4.0 et sa réutilisation (accordée bien entendue) s'inscrira dans ce cadre.

**Comment by quentinguidee** [comment]
Merci beaucoup! Oui, moi aussi pour éviter les soucis j'ai laissé la licence d'origine; c'est le plus sûr :smile:
