### ISSUE TITLE
"Ghost" characters

### ISSUE THREAD

**Issue by RedGl0w** [boricj/numworks-rpn#14]
In emulator and real calculator, when you push a number to a stack, the number you entered stays...
![image](https://user-images.githubusercontent.com/43498612/67147020-18194600-f291-11e9-81e1-3269c22ecdde.png)

**Comment by boricj** [comment]
I thoroughly reworked the app, this issue should be fixed. Keep #15 in mind until that particular issue is fixed in upstream epsilon.
