### ISSUE TITLE
Negative numbers in matrices

### ISSUE THREAD

**Issue by wawachief** [boricj/numworks-rpn#19]
I tried to type in a matrix in the RPN app. It seems to work except for the negative numbers. When I hit alpha+- for an element, the whole matrix is impacted. How can I put negative numbers in a matrix ?

**Comment by boricj** [comment]
On hitting alpha+- the input box gets committed to the stack and the opposite operation is applied to its top element, negating the entire matrix. A workaround is to enter the Python app, enter a single `-` on the console then copy its line. The minus sign can then be pasted in the RPN input box.

I'm not sure how to fix this. Unlike other graphical calculators, the NumWorks calculator doesn't have an dedicated opposite key, instead relying on the minus key and context. Perhaps deactivating the subtraction operator when the input box is selected and the cursor is not at the end of the buffer would be a reasonably intuitive compromise.

**Comment by wawachief** [comment]
Thank you for your answer. Why hitting alpha- has to commit the input box to the stack ? On rpn calcs, hitting +/- does not produce this effect : it inserts the minus sign at the beginning of the number under the cursor and stays in input mode.
deactivating the substraction operator does not feel very rpn : on the 48, hitting - with the cursor in the middle of a number executes the substraction.

**Comment by boricj** [comment]
I modified alpha+- to insert a minus sign instead of applying the opposite operation.
