### ISSUE TITLE
[Question/Suggestion] Matrices

### ISSUE THREAD

**Issue by Annwan** [boricj/numworks-rpn#8]
Bonjour,

Je souhaiterais savoir si l'application RPN supporte les calculs matriciels.

Si ce n'est pas le cas serai-ce faisable ?

Merci d'avance

**Comment by boricj** [comment]
De mémoire ça devrait marcher, dans le sens où le prompt RPN comprend les expressions en ligne et on devrait pouvoir entrer une matrice à l'ancienne (`[[1,2][3,4]]`). Je testerai ce soir si ça fonctionne en pratique.

**Comment by Annwan** [comment]
ok merci

**Comment by boricj** [comment]
J'avais oublié de fermer l'issue. On peut effectivement entrer une matrice sous format 1D dans RPN.
